title: Lizeth García Belmonte
logo: /assets/img/IMG_8469.JPG
description: Data Science Page.
show_downloads: true
google_analytics:

# Social Sharing
twitter:
  username               :@lizbelmonte

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true

  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true


theme: jekyll-theme-minimal

